export const PDF_WORKER_ACTIONS = {
  LOAD_PDF: 'LOAD_PDF',
  RENDER_PAGE: 'RENDER_PAGE',
  MERGE_PDFS: 'MERGE_PDFS',
  SPLIT_PDF: 'SPLIT_PDF',
  COMPRESS_PDF: 'COMPRESS_PDF',
  GET_PAGE_COUNT: 'GET_PAGE_COUNT',
  EXPORT_PDF: 'EXPORT_PDF'
}